### ISSUE TITLE
[question] crt shader that uses masks doesn't work properly in fullscreen

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#49] opened 2019-08-09 11:40 UTC
http://eab.abime.net/showpost.php?s=0d33b3358df041dd192ebb1d1e6173c6&p=1336107&postcount=246

quark-shaders: https://github.com/hizzlekizzle/quark-shaders

Is there a way to fix this?

**Comment by Screwtapello** [comment] 2019-08-09 11:59
Duplicate of issue #2?

**Comment by byuu** [comment] 2019-08-09 14:45
Yeah, the shader system needs to be updated. I had no choice but to add black margins in order to support adaptive sync with OpenGL. The problem is, shaders are out of my wheelhouse, so it's not going to happen unless someone well versed in shaders can sit down and work with me on updating them to the new system. I'll make whatever changes are needed to ruby/quark.

**Comment by Screwtapello** [comment] 2019-08-09 22:56
Closing as a duplicate of #2.

**Closed by Screwtapello** 2019-08-09 22:56 UTC
Labels: duplicate
