### ISSUE TITLE
Super Game Boy / ICD2: Emulation of $6003 ignores multi-player bits, MLT_REQ is handled in high-level emulation.

### ISSUE THREAD

**Issue by Bananattack** [byuu/bsnes#290] opened 2020-02-02 19:17 UTC
Hi! I'm currently working on a homebrew test program for the Super Game Boy that can upload custom SNES code and then use the Super Game Boy / ICD2 ports to communicate  back and forth between the SNES and GB.

There's a small longstanding issue with bsnes and higan with how multiplayer mode is activated, that makes it so that it only works if the Game Boy side first sends a MLT_REQ SGB packet through the joypad port.

Normally the packets sent through the SGB protocol are just data in the ICD2 that can be read out of port $7000..$700F, once port $6008 indicates a full 128-bit SGB packet is ready, and the interpretation of these packets is handled entirely in the Super Game Boy BIOS software. The Super Game Boy BIOS will write to port $6003 in order to toggle the 1P/2P/4P modes.

However, unlike all other packets that get handled by the Super Game Boy BIOS, in bsnes and higan, this one is specifically done as high-level emulation and is hardcoded into the emulator when it receives joypad port writes from the GB-side: https://github.com/byuu/bsnes/blob/1afd440c863c898afd2fcc6ad20d744436e89798/bsnes/sfc/coprocessor/icd/interface.cpp#L89-L104

This is probably a mistake, as these joypad packets have no special meaning to the ICD2 itself, they only have meaning to the program running on the SNES that interfaces with the ICD2.

Writes from the SNES program to the bits of ICD2 register $6003 that affect the 1P/2P/4P modes are presently are ignored, but these bits are mentioned in the comment above the code that handles this port: https://github.com/byuu/bsnes/blob/1afd440c863c898afd2fcc6ad20d744436e89798/bsnes/sfc/coprocessor/icd/io.cpp#L50-L68

The lack of direct $6003 write support currently makes it impossible for a custom SNES program to enable multi-player mode unless the GB sends a MLT_REQ first. However, on a real SNES running the Super Game Boy hardware, a custom 65816 program uploaded with DATA_TRN/DATA_SND + JUMP can use writes to $6003 to enable multi-joy mode in the ICD2.

[Among one of the possible reasons a custom homebrew might want to write $6003 from the SNES, is that an uploaded program can enable 2P or 4P mode to send custom data in the ICD2 joypad registers $6004 .. $6007, which can then be read out from the Game Boy side. And if the custom SNES program can enable multi-joy mode without the MLT_REQ asking for it, the GB side can use this as a verification that the new program is indeed uploaded and ready to communicate with, and potentially fall back on Super GB clone and emulators systems that don't have a true SNES hosting them.

For example, imagine a Super Game Boy enhanced game that comes with a special driver that can make full use of the SNES PPU and APU to make more powerful capabilities than the Super Game Boy BIOS allows, while still leaving communication open with the ICD2 ports so that the Game Boy can drive things. However, if it detects the host system doesn't actually emulate the full SNES, but still supports other SGB features (such as the case of a lot of GB-only emulators, or if a clone console existed with SGB support), it could fallback on a simplified mode with only borders or screen colorization, based on that information.]

While this probably won't affect any existing commercial games, being able to use this port as it works on a real SNES would open up new possibilities. And I'm not familiar enough with the code to know if this is true or not, but fixing this issue may also improve emulation of MLT_REQ packets from the BIOS too? I noticed this recent issue about it: https://github.com/byuu/bsnes/issues/77 -- so emulating at it the ICD2 port level itself might improve things.

Thanks for the help!

**Comment by byuu** [comment] 2020-02-03 00:44
Hi, so this looks like a really complex issue to tackle here @_@;;

I'm a bit swamped to look at it now I'm afraid, but I do know that endrift released a bunch of really interesting MLT_REQ SGB test ROMs. Perhaps someone feeling generous could take a look at which ones fail and help submit patches to correct them?

Otherwise, I'll try to get to this, but I think it might be a rather long wait, unfortunately. My backlog is pretty full ^-^;;

**Comment by Bananattack** [comment] 2020-02-05 06:08
No worries! It's definitely a bit complicated to get into these details of the SGB. So far I've made a couple test programs for SNES code uploading and it took a while to get started.

It looks like the `sgbdebug` branch of bsnes-plus has a fix for this! they had the same problem I reported here in their `master`. Although the codebases are laid out pretty different, the MLT_REQ mode-switching was handled similarly until this commit: https://github.com/devinacker/bsnes-plus/commit/59136f907fd16cba659e646daf6fdfcc766ffec9

Hopefully this change makes it easier to see what needs to be done. (I also don't know if I will get a chance easily, but I could try and migrate that bsnes-plus change to bsnes. I've never tried compiling from source)

--

If desired, I could maybe try to write a test ROM that interfaces with $6003 directly, and then confirm if the GB side changes id of its JOYP register. I had older test code for this at one point, but I'd need time to rewrite it.

A test ROM might be able to avoid writing custom SNES code at all, and just take advantage of the SGB BIOS: use GB-side DATA_SND to write values into $6003 in SNES address space. I don't know if the SGB BIOS software would prevent that, but I'm guessing it probably wouldn't care. Then, the test could try reading JOYP on the GB and figure out pass/fail depending (the results should pretty much work the same as issuing MLT_REQ).  So the detection could potentially be extremely close to the 'usual code' used to see if a SGB is attached (which issues a MLT_REQ, waits, and checks that the JOYP id started cycling), just need to replace MLT_REQ with a DATA_SND to $6003.

**Comment by Bananattack** [comment] 2020-02-06 08:15
I hope you don't mind me bumping this, but I've written a test program that can confirm a 2P switch by writing to $6003.

- Test Source: https://github.com/wiz-lang/wiz/tree/master/examples/gb/sgb_icd2_6003_test
- Test ROM: http://make.vg/get/homebrew/sgb_icd2_6003_test.gb

It seems DATA_SND directly to the register $6003 from the GB side won't work. Instead I needed to use an uploaded SNES program to test ICD2 hardware behaviour. The GB-side will send a request to the SNES side through the ICD2 framebuffer, which it acts on to write to $6003. The GB-side also sends text to display on the SNES, which changes if the outcome of the check is successful.

This ROM will show the message "TEST PASSED" running on real SGB hardware on a SNES. In bsnes, the ROM will just say "DETECTING 6003". On a GB emulator without any SNES-side emulation, only the GB side of the code will execute and no SNES upload, so it will look like garbage.

**Comment by devinacker** [comment] 2020-02-09 02:44
Just chiming in to say that I'm not aware of any regressions that the aforementioned bsnes-plus commit (https://github.com/devinacker/bsnes-plus/commit/59136f907fd16cba659e646daf6fdfcc766ffec9) introduced compared to the previous behavior, which I believe was the same as the current upstream behavior (which is, I think, based on endrift's test ROMs to some degree?) 

I can test any potentially tricky stuff and then submit a PR though, if you'd like. The only thing the change on my end does is set the number of players based on SNES-side writes to $6003 instead of basing it on detection of MLT_REQ packets on the GB side (as I understand it, that packet just instructs the SGB BIOS to write the appropriate value to $6003).

**Comment by byuu** [comment] 2020-02-09 16:55
Really, the thing that will help me the most is a PR patch, please. Just please confirm it's correct and won't break software. I would really appreciate any help with this ^-^;

I'm swamped with work on my fan translation, new emulator, and moving all my online aliases over. Plus real life work is pretty busy right now.

Barring this, I *really* appreciate the test ROMs! I will get to this as soon as possible if no one else does, but it will probably be a while longer ^^;

**Comment by byuu** [comment] 2020-02-19 15:14
Fixed in v114.4 thanks to devinacker.

**Closed by byuu** 2020-02-19 15:14 UTC

**Comment by Bananattack** [comment] 2020-02-20 06:54
This is great! Thanks @devinacker for making a patch to bsnes for this, and thanks @byuu for merging this upstream! Hopefully will get a chance to put this feature to use in homebrew projects soon.
