### ISSUE TITLE
Kishin Douji Zenki - Tenchi Meidou (Japan) - blackscreen [bsnes v110]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#124] opened 2019-09-22 10:25 UTC
bsnes, Mesen-S and higan v106:

![image](https://user-images.githubusercontent.com/53529402/65385854-e1a0e780-dd33-11e9-994f-7d86feb6fee3.png)

Hardware and snes9x v1.60:

![image](https://user-images.githubusercontent.com/53529402/65385861-f3828a80-dd33-11e9-913f-23388287e42f.png)

**Comment by byuu** [comment] 2019-09-22 14:55
Tagging @SourMesen.

Okay, this one *sucks*. The SMP has a loop that writes to $f1 (clear PORT1), then reads $f4-f7 and ORs them together. Meanwhile the CPU has a loop that constantly writes #$10 to $2141 (set PORT1.)

The only way to break the loop is if the CPU write does not occur between the SMP clear->read.

This is obviously a game bug because this behavior is psychotic and unintentional, but it's what it does.

The way to get it to work is to emulate bus hold delays with the SMP: similar to the CPU, writes have to trigger at the end of bus cycle, whereas reads have to trigger earlier. This gives a narrower gap between a write to $f1 and a read from $f5.

Good grief ._.

Fixed in the next WIP.

[notes.txt](https://github.com/byuu/bsnes/files/3639860/notes.txt)

**Comment by SourMesen** [comment] 2019-10-07 02:01
@byuu  Hey, just wanted to say thanks for tagging me in these and describing the causes/fixes!  Been away and taking a break for a couple of months, but will hopefully slowly get back into Mesen(-S) dev in the coming days/weeks, so I should be able to get to these relatively soon (a lot has piled up over the past months :p)

**Comment by byuu** [comment] 2019-10-26 23:06
@SourMesen no problem, also see:
http://forums.nesdev.com/viewtopic.php?f=12&t=18005&p=243473#p243473
It looks like something more complex is going on, hopefully you might be able tp help ^-^;;

**Comment by byuu** [comment] 2019-10-27 04:28
This broke blargg's SMP/DSP test ROMs, so I reverted it, which means Kishin Douji Zenki - Tenchi Meidou is broken again.

**Comment by FitzRoyX** [comment] 2019-10-28 09:12
byuu, you know that I did full library tests years ago, right? This game worked then, which means it was working at the same time as blargg's tests. So... why did you try fixing the game as if it has always 
been broken? :P

higan 099 plays kishin and also passes blargg's SMP test. higan 104 hangs kishin and fails the SMP test. I don't have the versions inbetween, but changelogs indicate some likely culprits:

> higan v103 fixed a few S-SMP instruction bugs and changed the brightness of the darkest luma setting.
> higan v104 separated the S-SMP's IO ports so that they aren't literally the same as the APU RAM bytes at the same addresses and changed the latching behavior of some PPU background registers.

**Comment by FitzRoyX** [comment] 2019-10-28 13:40
I found v103 after some googling. Kishin works and SMP passes. First sign of breakage is indeed 104.

**Comment by byuu** [comment] 2019-10-31 00:21
//works with Kishin Douji Zenki, breaks blargg's smp_mem_access_times
    auto SMP::read(uint16 address) -> uint8 {
      step(12);
      uint8 data = readRAM(address);
      if((address & 0xfff0) == 0x00f0) data = readIO(address);
      step(12);
      return data;
    }

    //works with blargg's smp_mem_access_times, break Kishin Douji Zenki
    auto SMP::read(uint16 address) -> uint8 {
      step(12);
      uint8 data = readRAM(address);
      if((address & 0xfff0) == 0x00f0) data = readIO(address);
      step(12);
      return data;
    }

Fun.

**Comment by byuu** [comment] 2019-10-31 02:00
Okay, I added a workaround fix.

    //Kishin Douji Zenki - Tenchi Meidou requires bus hold delays on CPU I/O reads.
    //smp_mem_access_times requires no bus hold delays on APU RAM reads.
    if((address & 0xfffc) == 0x00f4) {  //0x00f4 - 0x00f7
      wait(address, 1);
      uint8 data = readRAM(address);
      if((address & 0xfff0) == 0x00f0) data = readIO(address);
      wait(address, 1);
      return data;
    } else {
      wait(address, 0);
      uint8 data = readRAM(address);
      if((address & 0xfff0) == 0x00f0) data = readIO(address);
      return data;
    }

The second argument to wait is "half cycles", eg only take 12 clocks instead of 24 clocks (exact amount is based on the TEST register settings, but in 100% of cases, it's always 12/24.)

So what's actually happening here is that SMP reads from internal functionality (eg timers and RAM) is faster than SMP reads from the shared CPU I/O ports.

I'm simulating this with the above address check, because short of someone sending me an SNES modified to use a single crystal oscillator used by both the SNES CPU and SMP, I can't really write more exacting tests to get the exact values here.

This is definitely one of the most extreme edge cases so far in SNES emulation.

Tagging @SourMesen once more with the workaround.

**Closed by byuu** 2019-10-31 02:00 UTC
Labels: help wanted
