### ISSUE TITLE
DKC2- Missing faces on character barrels

### ISSUE THREAD

**Issue by kev4cards** [byuu/bsnes#10] opened 2019-07-20 19:31 UTC
Byuu,

In the Klobber Karnage level of DKC2 (bonus level accessed through the kiosk in Krazy Kremland), at least one set of the Diddy/Dixie barrels will flicker or be faceless if you fly over them with Dixie when they are initially off-screen.

I'm using OpenGL with VSync off and synchronized WASAPI audio.

Specs: i7-8750H, GTX 1060, 144 Hz screen

Attached are screenshots of the area where the issue can be most easily be reproduced. If you start flying from the upper platform past the barrel kremlins, you'll see the character barrels flicker (sometimes the barrel itself, other times just the faces, or even no faces for a second or so). It's not 100% consistent, though. It might happen 20% of the time or so (starting from a save state with the barrel kremlins present).

I can provide save states if need be through a file hosting link.

EDIT: Screenshots are uploading correctly right now.

**Comment by Screwtapello** [comment] 2019-07-20 22:30
What version of bsnes are you testing with? I wonder if this is related to https://github.com/byuu/higan/issues/1

I can't see any screenshots, or links to them. Note that you shouldn't need a file-hosting link, you should be able to just paste an image from the clipboard directly into the text box as you're writing a comment, or drag and drop an image file from Windows Explorer into the box.

**Comment by kev4cards** [comment] 2019-07-20 23:09
Sorry. I think i had an extension interfering with the upload. The zip contains the .bmp images along with the save states and normal save file. I am using version 107.1.

I think it probably is related to the issue listed under higan (can't say for sure, though). 

[DKC2-barrel_flicker.zip](https://github.com/byuu/bsnes/files/3414050/DKC2-barrel_flicker.zip)
![Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)-001](https://user-images.githubusercontent.com/21962903/61585049-094fb580-ab21-11e9-824e-55c2c3cef507.jpg)
![Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)-002](https://user-images.githubusercontent.com/21962903/61585050-094fb580-ab21-11e9-9af2-127d9d9bf899.jpg)

**Comment by byuu** [comment] 2019-07-21 10:59
Hmm, I've been making OAM changes so we should see if this issue still occurs in v108, and if so, whether it's with the fast PPU, slow PPU, or both. If the issue is still there, I'll try to dig into a fix for this. Thanks for the report!

**Comment by kev4cards** [comment] 2019-07-21 18:06
The issue happens pretty much every time with the fast PPU. It's more inconsistent on the slow PPU. I'm resetting through the save state to check the issue instead of starting from load and playing through the level. Hopefully, the issue is fixed with the new changes and won't show up in v108.

Also, I'm using Windows 10 version 1803 (April 2018 update) if that is important at all.

**Comment by kev4cards** [comment] 2019-07-29 00:11
I checked with v108. The problem still occurs. You will need to get the barrel kremlins to hit the wall first, making sure you avoid having the character barrels show up on the screen. Then, jump high with Dixie on the left third of the high platform and fly over to the character barrels. If you fly over with the barrel kremlins sitting still, the problem won't show up. This is happening on both fast and slow PPU still.

**Comment by byuu** [comment] 2019-07-29 13:59
Hmm, then I'm really not sure. Sounds extremely difficult to trigger and worth confirming on real hardware before proceeding.

**Comment by byuu** [comment] 2019-07-29 14:01
Marked help wanted: can someone test this on real hardware please?

**Comment by kev4cards** [comment] 2019-07-29 23:57
My SNES is in storage, so I will unlikely be able to test it out anytime soon. 

Here is a video of what is likely real hardware on that level at the point in question (playing on a CRT): https://youtu.be/BC5Y8cIPON4?t=77.

If I get the TNT klobber on the upper platform to move down and wake up the other two barrel klobbers (to mimic what is done in the video) and then fly starting near the right cliff of the upper platform, I can make the banana coin disappear and the rotating barrel to flicker. In this scenario, the character barrels are okay.

Lastly, here is some relevant information from the manifest viewer:  region:   SNS-ADNE-USA, revision: SNS-ADNE-1, board:    SHVC-BJ1M-20

**Comment by kev4cards** [comment] 2019-08-01 01:05
I found a few more spots with flickering barrels or missing graphics on barrels. First is the hidden bonus stage barrel at the end of Klobber Karnage (past the level-end target). It is missing the "B" graphic on it. I can reproduce this consistently.

The other spot is in the second level of the game, Mainbrace Mayhem. Once you exit the first cannonball bonus stage, head back down the level until the point with the line of seven rats. If you fly over them down the slope, either the save barrel or the throwing barrel will flicker. That said, it is hard to reproduce this consistently. Also, the game slows down tremendously for me when flying over that many rats. Real hardware videos do not show this slowdown.

**Comment by SourMesen** [comment] 2019-08-04 13:20
So far this kind of looks like the game might be somehow struggling to keep up with the stuff that's on screen (3 monsters + 2 barrels + both characters).  Even abusing save states, getting the barrels to appear incorrectly isn't exactly easy, either, so I'm not really convinced the video proves that this doesn't happen on hardware.

I'm assuming we're talking about this?
![image](https://user-images.githubusercontent.com/21093973/62424146-c05b3d80-b698-11e9-88b7-3a3dfce38d81.png)

The sprites are missing from VRAM/OAM too, so this doesn't sound like a PPU problem:
![image](https://user-images.githubusercontent.com/21093973/62424157-e680dd80-b698-11e9-9882-612cb5f0d14e.png)

**Comment by kev4cards** [comment] 2019-08-04 19:16
I agree that the YouTube video does not guarantee that this does not happen on real hardware. It was just the closest thing I could find to the described scenarios.

Also, I recognize the difficulty in trying to reproduce the problem. It is just something I stumbled upon when playing through the game a few months ago. That said, the screenshot shows the problem effectively. It can also be the banana coin or the curved arrow on the rotatable barrel to the right if you start flying from the right end of the upper platform. Moreover, it is possible to have the curved arrow on the rotatable barrel remain disappeared throughout its platforming section/track if you fly into it while the arrow is missing (on Mesen-S at least and really hard to make happen).

The weird part about the issue in Klobber Karnage is that I do not experience any slowdown. However, I do experience a slowdown with the seven rats in Mainbrace Mayhem (along with the barrels at the bottom of the slope flickering if I work it just right). So, maybe the graphical glitches show before a slowdown happens (with more sprites in that section of Mainbrace Mayhem than the Klobber Karnage area) (asking out of ignorance)?

All in all, it would be nice to see the hardware or emulator problem fixed in some way by someone (with a rom hack or a "correct SNES hardware problems" feature).

**Comment by byuu** [comment] 2019-08-04 21:46
I really appreciate the help looking into this, Sour.
kev, I don't know how we can prove it doesn't happen on hardware, but at this time, I'm inclined to agree with Sour. I'll leave this issue open for a bit in the event someone with real hardware is up for testing it to try and reproduce it, but if we have no takers, then I don't have the bandwidth to investigate further I'm afraid.

**Comment by kev4cards** [comment] 2019-08-05 00:37
I can try to get on reddit and post something to a few relevant subreddits. That might get more eyes on the matter. Hopefully, someone there can test it out on a real SNES to see what the outcome will be. I think the missing barrels/faces will happen. 

I wasn't expecting to find an in-game glitch that hasn't been already reported given this game's age and popularity. I assume the memory for sprites becomes full (or nearly full), so new sprites will not be drawn until some memory frees up. Is that more or less correct?

Obviously, the "maybe" bug is not a huge issue to me. It is just a bit perplexing this hasn't been surfaced until now.

**Comment by Dwedit** [comment] 2019-08-05 06:33
Does this bug happen in the Japanese version of the game?  That's the only copy I got.

**Comment by coolthxmcdoom** [comment] 2019-08-05 06:41
I tested this a few times on my SNES and I seem to get a sprite issue in that area of Klobber Karnage fairly consistently. It usually just seems to be the faces and barrels appearing late, not necessarily a flicker by my definition. Here's a link to a YouTube video of one of the times I was able to make this happen with both barrels. Can you confirm/ deny this is the sort of thing you were seeing in the emulators, kev4cards? 

https://www.youtube.com/watch?v=dsI_I_HPJ3Y

If you'd want/ need to know my exact SNES and/ or DKC2 cart revision for whatever reason I can provide that sometime later when I'd have time to take them apart.

I also tried to do the thing you mentioned in Mainbrace Mayhem but I couldn't seem to get the barrel sprites to act up for me. The slowdown was present, however.

**Comment by SourMesen** [comment] 2019-08-05 11:54
That video looks exactly like the bugs I was able to reproduce yesterday, so it sounds like this might just be a bug with the game itself, after all.

**Comment by kev4cards** [comment] 2019-08-05 19:24
coolthxmcdoom, that checks out with me, too. The only things of note that might be ever so slightly different on my side are the sprites might come in at half a barrel at a time on a cold start and there can be a little microstuttering more often than not. I think that might be Windows playing interference a bit. This is for bsnes v108.3 (commit 216b47). Mesen-S v0.2.0.17 seems to handle late sprite generation better (i.e. not encountering any microstutter or barrels coming half at a time).

As far as Mainbrace Mayhem goes, Dixie has jump at the right height and the rats have to be in line without any gaps. It is really hard to make it happen. Dixie will fly at about roughly half speed when done right and the save or throwing barrel will appear late (keep on wanting to say flicker). That said, using Diddy's cartwheel attack while going up the slope with all of the rats seems normal with the minor slowdown I remember from when I was a kid.

Thanks for everyone's help to confirm that this is happening on real hardware. Although, I was kind of hoping to say that byuu's emulator is not perfectly bug-free yet, heh (silly face).

**Comment by byuu** [comment] 2019-08-05 22:34
None of my emulators are perfect, and code cleanups / optimizations often cause temporary regressions. Anyway, sounds like we can close this for now, thanks everyone!

**Closed by byuu** 2019-08-05 22:34 UTC
