### ISSUE TITLE
Freezing and unable to hold button with Run-Ahead in v111.9

### ISSUE THREAD

**Issue by Kerst1** [byuu/bsnes#177] opened 2019-10-16 12:36 UTC
**Steps to reproduce:**

1. Unpack and start bsnes_v111r9-windows
2. System>Load Game ...>Mega Man X (U) (V1.0) [!].smc
3. Press 'Enter'-key a few times until you get in-game
4. Hold down 'A'-key (Mega Man charges a shot)
![1](https://user-images.githubusercontent.com/56637456/66919349-77711f00-f021-11e9-846e-5bcd3efefe73.png)
5. Settings>Enhancements>Change Run-Ahead from 'Disabled' to 'One Frame'
6. hold down 'A'-key (Mega Man does not charge his shot, instead shoots about 2 normal shots per second)
![2](https://user-images.githubusercontent.com/56637456/66919352-7809b580-f021-11e9-8ff7-ed1c500ae958.png)
7. Hold 'Right arrow'-key until Mega Man falls off edge. (Game freezes on a black screen)
![3](https://user-images.githubusercontent.com/56637456/66919355-7809b580-f021-11e9-8f65-88ca7c808fbe.png)
![4](https://user-images.githubusercontent.com/56637456/66919357-7809b580-f021-11e9-8ae1-ef602988d3ac.png)

Performs the same on three tested systems: 
Win 10 v1803, Core 7200U
Win 10 v1903, Ryzen 3700X
Win 10 v1903, Ryzen 3700X

**Comment by Screwtapello** [comment] 2019-10-16 13:11
I built commit 9f86a3b on Linux, loaded "Mega Man X (USA)" (which should be the No-Intro name for that game), but I could not reproduce this problem. After setting Run Ahead from Disabled to One Frame, the charge shot still worked as expected, and falling into the first pit just respawned me at the beginning of the level.

**Comment by Kerst1** [comment] 2019-10-16 13:55
Thanks Screwtapello for trying it out. I tried it on a third computer (also Win 10 v1903, Ryzen 3700X).
This time I used both "Mega Man X (USA).sfc" and "Mega Man X (USA) (Rev 1).sfc" from No-Intro. I was able to reproduce the same issue.

**Comment by Screwtapello** [comment] 2019-10-16 22:51
I linked this issue on the official Discord, and many other Windows users were able to reproduce it, too.

**Comment by byuu** [comment] 2019-10-16 22:58
It's also not triggering for me here. There's clearly an issue, so I'll try to find a PC I can reproduce the issue on. In the mean time if anyone else with programming skills can reproduce this, help would be very much appreciated ^-^;;

**Comment by kev4cards** [comment] 2019-10-16 23:59
I was able to reproduce the problem also (Win 10 v1903, core i7-8750H). Furthermore, I unloaded the game and then closed the emulator with no change to the settings. Upon re-opening the emulator and selecting Mega Man X (USA) (Rev 1) from the "load recent game" menu, the game freezes on the first screen (copyright/license).

**Comment by byuu** [comment] 2019-10-17 05:59
Hello, I fixed the issue in v111.10, which is up on https://bsnes.byuu.org as a Windows binary and source code. I will commit the fix to GitHub in a few hours, I'm having some PC issues with the box I use with Git.

**Comment by byuu** [comment] 2019-10-17 06:00
Actually, I should leave this open until I can submit the Git change.

**Comment by Kerst1** [comment] 2019-10-17 06:01
Thanks, I've tried it and Run-Ahead in v111.10 is working beautifully now.

**Comment by byuu** [comment] 2019-10-17 16:07
It's fixed now in Git too, thanks everyone!

**Closed by byuu** 2019-10-17 16:07 UTC
