### ISSUE TITLE
--fullscreen command-line option does not work

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#79] opened 2019-09-03 01:11 UTC
The `--fullscreen` command-line option does not work. bsnes v108 (including the latest 108.15 nightly) starts in windowed mode regardless of whether this option is specified. This takes place regardless of whether bsnes is started with a specific rom specified:

    bsnes.exe --fullscreen "D:\example\game.zip"

or just bsnes is started:

    bsnes.exe --fullscreen

Same with the latest higan 106.208 nightly.

**Comment by byuu** [comment] 2019-09-03 02:57
It works in bsnes v108.15.

higan v106.208 doesn't support command-line game loading anymore.

**Comment by Max833** [comment] 2019-09-03 13:24
> bsnes v108 (including the latest 108.15 nightly) starts in windowed mode regardless of whether this option is specified.

I can confirm that (Windows 10 Pro, version 1903).

**Comment by Marat-Tanalin** [comment] 2019-09-03 19:03
Tested on another computer with two different versions of Windows — 7 Home Premium and 10 Pro (both are 64-bit).

In bsnes v108.15 and v108.17, `--fullscreen` does work if the game is specified in command line, but does NOT work if the game is NOT specified.

That said, if the game is specified, the emulator first starts in windowed mode anyway, THEN after a few moments switches to full-screen mode, while the expected behavior is that bsnes should start directly in full-screen mode.

In the stable v108, `--fullscreen` does NOT work at all — regardless of whether the game is specified.

And Fwiw, under Windows 7, v108.15 crashes after closing it IF the emulator was started with `--fullscreen` and a game specified, while does not crash under Windows 10 under the same conditions. Fortunately, v108.17 does not crash even under Windows 7, so the crash issue is probably fixed which also means that there were some full-screen-related changes between v108.15 and v108.17.

> higan v106.208 doesn't support command-line game loading anymore.

Is `--fullscreen` supposed to work in bsnes/higan if a game is NOT specified? According to [documentation](https://higan.readthedocs.io/en/latest/interface/higan-cli/) , it is:

> When launched with --fullscreen, higan will automatically enter fullscreen mode when it starts, otherwise it starts in windowed mode. This is not much use unless you also specify GAME, because you won’t be able to load a game until you exit fullscreen mode by pressing the “Toggle Fullscreen” hotkey.

But in fact it does not work unless the game is specified.

**Comment by byuu** [comment] 2019-09-03 22:52
>In bsnes v108.15 and v108.17, --fullscreen does work if the game is specified in command line, but does NOT work if the game is NOT specified.

That's by design. There is no reason to dump someone into a black screen with no visible options to load a game.

>That said, if the game is specified, the emulator first starts in windowed mode anyway, THEN after a few moments switches to full-screen mode, while the expected behavior is that bsnes should start directly in full-screen mode.

I sympathize it'd be nicer to go right to full-screen, but I create the initial window first to get context handles needed for DirectSound, DirectInput, etc. The window must be visible onscreen before the handles are valid. The fullscreen windows are transient and get destroyed when exiting fullscreen. So, nice as it would be, this is a won't fix, sorry.

>In the stable v108, --fullscreen does NOT work at all — regardless of whether the game is specified.

v109 will be out soon.

>Is --fullscreen supposed to work in bsnes/higan if a game is NOT specified? According to documentation, it is:

The docmentation was made for v106. The reason I'm at over 200+ WIPs with higan is that I'm in the process of writing a new GUI. We will need new documentation once higan v107 is released.

**Comment by byuu** [comment] 2019-09-06 01:46
Doesn't seem to be anything more to do here.

**Closed by byuu** 2019-09-06 01:46 UTC
