### ISSUE TITLE
[Super Game Boy] Zen - Intergalactic Ninja (USA) graphic glitch

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#91] opened 2019-09-06 08:53 UTC
using v 109
going through the super gameboy
during the intro the head is too far down
you are supposed to see his mouth and neck
![zen](https://user-images.githubusercontent.com/2696404/64414874-bfb62c80-d0c6-11e9-8ca5-3252686a0cdd.PNG)
this from the gameboy
![zen1](https://user-images.githubusercontent.com/2696404/64414897-c9d82b00-d0c6-11e9-9c0a-427633f325ea.PNG)

**Comment by endrift** [comment] 2019-09-09 06:48
Isn't this a dupe of https://github.com/LIJI32/SameBoy/issues/90 ?

**Comment by byuu** [comment] 2019-09-19 06:18
Issue with SameBoy, not bsnes.

**Closed by byuu** 2019-09-19 06:18 UTC
