### ISSUE TITLE
Flickering backgrounds in Donkey Kong Country games

### ISSUE THREAD

**Issue by sharknnth** [byuu/bsnes#150] opened 2019-10-07 21:41 UTC
Hi, I've come across a glitch that the background layers of skies can flicker in and out in the DKC games. It's very apparent in Donkey Kong Country 3 on the over map and the flickering's bad on the file select screen of DKC3. This glitch isn't present in bsnes 110.

**Comment by byuu** [comment] 2019-10-08 01:31
This may be a bug I've fixed in v111.1-3. Can you try again with v111.3?
https://bsnes.byuu.org/#download

I cannot reproduce this issue with either the fast or accurate PPU renderers in either DKC2 or DKC3.

**Comment by underwaterworldjungle** [comment] 2019-10-08 07:30
I experience this bug in the DKC games after I updated to v111.3. It wasn't in v111.2. Very bad flickering of a background layer. In DKC3 it starts from the music-wheel intro animation in accuracy mode, It also occurs in fast mode though it seems not as much - for example, the DKC3 intro does not glitch in fast PPU. I'm using OpenGL.

**Comment by underwaterworldjungle** [comment] 2019-10-08 13:14
I'm guessing it's the same bug; Super Mario Kart is unplayable because of flickering, positioning and rotational glitches once in a race. Fast and accurate PPUs.

**Closed** 2019-10-08 16:00 UTC

**Comment by jjfmz42015** [comment] 2019-10-08 19:26
I was using the settings bml from the official release to test. Didn't realize it was a rewind issue. Maybe in the future ship with rewind off?

**Comment by Max833** [comment] 2019-10-08 19:32
I'm pretty sure it's is disabled by default.

**Comment by jjfmz42015** [comment] 2019-10-08 19:34
Well then I didn't have it on
