### ISSUE TITLE
Star Ocean - random freezes and character flickering [bsnes v111][Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#142] opened 2019-10-05 13:33 UTC
Unfortunately, it's impossible to reproduce this constant. Best of all would be to play the first 5 minutes of the game with the rewind function a few times. 

**Random freezes:**
Intro: https://streamable.com/10j6u
Third battle: https://streamable.com/kv07a

**Character flickering:**
https://streamable.com/cke2f

**Comment by byuu** [comment] 2019-10-05 16:25
The freezes, 9:10 odds it's the "fast DSP" option. Try turning that off and see if it works.
It's a nice speedup, but given this is the third game to have issues with it, I think I'll disable it out of the box, and also add an exception for Star Ocean in case folks re-enable it.
anomie's sample-based DSP worked perfectly fine with all games, but it seems something about blargg's really doesn't like this speedhack.
I'll look at the sprite issue later. Ballpark guess, did you disable the sprite limit maybe?

**Comment by Max833** [comment] 2019-10-05 17:47
> The freezes, 9:10 odds it's the "fast DSP" option. Try turning that off and see if it works.

Yes, this was the first thing I did, but it turns out this wasn't the problem. For example, this did happen with Fast PPU, audio and coprocessors off: https://streamable.com/n3inm

> I'll look at the sprite issue later. Ballpark guess, did you disable the sprite limit maybe?

Not always, but I can reproduce this now with these settings (screenshot) every time, yeah. Seems like the problem isn't just about character: https://streamable.com/jxu9z
 
![image](https://user-images.githubusercontent.com/53529402/66258655-27d05f00-e7a8-11e9-8d7f-e9716bf57df2.png)

**Comment by byuu** [comment] 2019-10-05 23:21
There's a possibility this is a Windows compiler bug, but it's not a problem with bsnes itself. I get no sprite flickering or freezes regardless of settings.

![Screenshot_2019-10-06_08-19-50](https://user-images.githubusercontent.com/2107894/66261945-23d92700-e812-11e9-89ca-bae859cb2e79.png)

**Comment by Max833** [comment] 2019-10-05 23:56
> I get no sprite flickering or freezes regardless of settings.
Maybe try the nightly binary and see if the issue goes away? That'd be a different compiler used than mine.

Same result. Anyway, thanks for your efforts! :)

**Comment by byuu** [comment] 2019-10-06 00:25
Well then I give up.

**Comment by byuu** [comment] 2019-10-06 06:47
There is no issue with the fast PPU, the flickering is caused by the accurate PPU's recent sprite latching emulation.

**Comment by byuu** [comment] 2019-10-06 09:16
Okay, I fixed it.

There were two issues causing sprite flickering: one was failing to latch FirstSprite at the start of each scanline, the other was not rendering tiles inside overscan (V=224-239) when overscan was disabled.

The freezing is a tougher long-standing issue with bsnes save states. For whatever reason, desynchronizing things by one opcode periodically causes Tales of Phantasia and Star Ocean to lock up. So basically, you can't have rewind enabled for those two games. A much longer-term solution is needed for cooperative-threaded save states, but for now, basically don't use the rewind feature with these two games, and I'll add some code in a future WIP to force-disable it to be extra safe. But since bsnes ships with rewind off for exactly this reason, I feel it's okay for now to mark this resolved in the official releases.

**Closed by byuu** 2019-10-06 09:16 UTC

**Comment by byuu** [comment] 2019-10-07 05:06
I fixed the stability issue with rewind as well. So we should be totally good on this bug now.

**Comment by Max833** [comment] 2019-10-07 14:12
Yeah, everything works without problems! Thank you, byuu! =)
