### ISSUE TITLE
Audio buffer drop outs

### ISSUE THREAD

**Issue by armak** [byuu/bsnes#22] opened 2019-07-28 17:58 UTC
The audio playback suffers from buffer overruns, causing silent gaps in the audio buffer.This happens with every driver option that works, which in my case is all of them except ASIO, which causes Bsnes to crash. My audio interface is a Focusrite Scarlett (which has its own official ASIO driver).

Out of the non-crashing drivers WaveOut and DirectSound are especially bad. WASAPI works somewhat better but still produces about 30 such dropouts for 1 minute 30 seconds of audio based on my statistics, making the audio quality and game playing experience quite disappointing. An example:

![image](https://user-images.githubusercontent.com/4991927/62010875-392e3700-b179-11e9-9297-d71dd8f4db97.png)

This example uses WASAPI running at 44100Hz (the set sound playback frequency in Windows) at a latency of 100. The length of each of the silent gaps with these settings is 440 samples. Using latency 20 makes the gaps 352 samples long, and they occur about as frequently.

These issues are reported under the version v108, but previous versions v107 and v106 also produce similar (in my recollection somewhat worse) behavior. Emulators with—to my understanding—cycle-accurate audio emulation such as Snes9x don't have this issue.

I'm using a Ryzen 2700X running at about 4Ghz, Windows 10 1903 64-bit. I'm not running any other CPU consuming or audio playing applications simultaneously.

**Comment by byuu** [comment] 2019-07-28 18:49
ASIO drivers are horrendously buggy. My ASIO code follows their SDK example 100% to a tee, but crashes inside driver DLLs (per backtraces) even though the previous function returned an OK status, and the current function provides good arguments. I tried to get help from Steinberg but they weren't interested in a small-time dev. I'm told from professional audio devs that ASIO drives require lots of workarounds, but I'm not privvy to their secrets.

I don't know what's going on with your sound hardware, but it's definitely not reproducable on most peoples' computers. I would definitely notice if the audio kept cutting out 20+ times a minute, and I would never release software that behaved that way on any of my systems.

It's very weird that Snes9X avoids this on your system, because bsnes and Snes9X share virtually identical waveOut and XAudio 2.1 audio drivers.

I'll leave this open in the event someone else has a similar issue and might be able to help diagnose this further, but I'm afraid I can't fix this without being able to reproduce your issue at all.

**Comment by byuu** [comment] 2019-07-28 18:52
Oh, I might know what it is.

Is your video driver forcefully syncing to Vblank anyway?

Try setting your video driver to "None", and see if it fixes the audio, please.

**Comment by armak** [comment] 2019-07-28 19:20
> ASIO drivers are horrendously buggy. My ASIO code follows their SDK example 100% to a tee, but crashes inside driver DLLs (per backtraces) even though the previous function returned an OK status, and the current function provides good arguments. I tried to get help from Steinberg but they weren't interested in a small-time dev. I'm told from professional audio devs that ASIO drivers require lots of workarounds, but I'm not privvy to their secrets.

This is fine for me honestly, WASAPI especially should be more than fine for this kind of use (just thought I'd report that I can't try that option to see if it would help).

> I'll leave this open in the event someone else has a similar issue and might be able to help diagnose this further, but I'm afraid I can't fix this without being able to reproduce your issue at all.

I could try looking into it myself too if you have build instructions for Windows available (could not see any at a cursory glance).

> Try setting your video driver to "None", and see if it fixes the audio, please.

It seems to actually, yeah. I'm using the default OpenGL 3.2 video driver with both "Synchronization" and "GPU Sync" enabled. Enabling or disabling either setting doesn't seem to make a difference as far as the audio is concerned, but I have to leave at least the latter enabled or otherwise the video output has massive frame drops.

But yeah disabling the video output entirely seems to resolve the audio issue, or at least I didn't hear any dropouts after listening to it for a few minutes and Audacity would confirm this.

I have an NVIDIA GPU and I did have Vsync forced on in the Control Panel. Turning it off and running Bsnes in Fullscreen (should be exclusive mode, as opposed to windowed where Windows forces vsync on) it might be a little better? Hard to say, I still hear some dropouts but I think it's a bit more infrequent. In any case the issue seems to be related to this anyway since using the null driver helped.

**Comment by byuu** [comment] 2019-07-28 20:02
Compiling bsnes on Windows requires installing msys2, gcc8, and if you want to grab the source quickly, git helps (but it's not needed.)

Then just go into the bsnes folder and run "make -j8", and the binary will be in bsnes/out.

**Comment by byuu** [comment] 2019-08-26 13:47
Will mark as closed for now. There's really not much I can do for this.

**Closed by byuu** 2019-08-26 13:47 UTC
