### ISSUE TITLE
The latest version "v109" is crashing a lot

### ISSUE THREAD

**Issue by xZabuzax** [byuu/bsnes#100] opened 2019-09-08 05:51 UTC
bsnes v108 and below never crashed for me but the latest version v109 is crashing a lot. Sometimes it crash when I quit the emulator and sometimes it doesn't crash, I'm not sure what's causing this but the crash is random. The culprit appears to be "ntdll.dll".

Here's a picture of the crash:
https://imgur.com/WB9wT1w

Here's my PC Spec in case someone ask:

[CPU]: Intel Core i7-4790K 4.0GHz
[GPU]: EVGA GeForce GTX 970 Superclocked ACX 2.0 4GB GDDR5
[PSU]: EVGA SuperNOVA G1 1000W (80 Plus Gold)
[RAM]: Corsair Vengeance 16GB (2x8GB) DDR3 1600MHz
[MOBO]: MSI Z97-GAMING 5
[PC CASE]: ENERMAX Ostrog GT (Red)
[CPU FAN]: Cooler Master: Hyper 212 EVO
[OS]: Windows 7 Ultimate (64-bit)

**Comment by byuu** [comment] 2019-09-08 06:35
If you want me to fix it then I need a gdb backtrace to see what is causing it. If anyone this is happening to can provide that, please do so.

**Comment by xZabuzax** [comment] 2019-09-08 06:49
> If you want me to fix it then I need a gdb backtrace to see what is causing it. If anyone this is happening to can provide that, please do so.

Can you please tell me how can I provide that info? I will be more than happy to provide it as long as the process is not complicated.

**Comment by byuu** [comment] 2019-09-08 10:39
Would need to be a developer, really ... it's okay, let's give it some time and see if anyone can chime in before we go that far. Appreciate your willingness to help though!

**Comment by bajolzas** [comment] 2019-09-08 17:34
I can confirm bsnes is crashing on me, so far only when messing with the settings (I get no crashing error though, it just closes without saving my changes)

**Comment by byuu** [comment] 2019-09-09 13:23
![log](https://user-images.githubusercontent.com/2107894/64534310-30bc4500-d350-11e9-810d-59f5c2500b92.png)

I gave it everything I had, but I can't fix this. It's crashing when checking a boolean value inside a non-threaded application (there is nothing deallocating at the break statement.)
It crashes at -O1, but not at -O0. Setting InputManager::poll() alone to optimize at O0 doesn't work.

So unless someone else can figure something out, I guess we're just screwed.

**Comment by jjfmz42015** [comment] 2019-09-09 14:49
> ![log](https://user-images.githubusercontent.com/2107894/64534310-30bc4500-d350-11e9-810d-59f5c2500b92.png)
> 
> I gave it everything I had, but I can't fix this. It's crashing when checking a boolean value inside a non-threaded application (there is nothing deallocating at the break statement.)
> It crashes at -O1, but not at -O0. Setting InputManager::poll() alone to optimize at O0 doesn't work.
> 
> So unless someone else can figure something out, I guess we're just screwed.

On 3 different machines both Win 7 and Win 10 no crashing at all here if its worth anything to say this

**Comment by orbea** [comment] 2019-09-09 15:56
> It crashes at -O1, but not at -O0. Setting InputManager::poll() alone to optimize at O0 doesn't work.

I have not reproduced this, but try disabling the optimization for every file in the code base and then gradually reduce the files without optimizations until you narrow it down to 1 file. Again repeat this with `#pragma` until you narrow it down to specific code in the file or includes. This will hopefully narrow down where this is happening better.

I think the options are you are doing something undefined or you found a compiler bug...

**Comment by Marat-Tanalin** [comment] 2019-09-09 23:32
Yeah, bsnes v109 crashes at least under **Windows 7** on **Core i-2100T** with **8GB** of RAM and GeForce **GTS 250 2GB**. The previous v108 was crashing too. Most often this happens when **closing bsnes**.

**Comment by jjfmz42015** [comment] 2019-09-10 01:14
not being a Troll. Truly no crash here. chaned settings a ton of times, switched beetween accuate and fast ppu. played asp, smw,sm kart, super turrican 2, tmnt iv

exit and restart emu like crazy not a single crash


test rig
windows 7 sp1 ultimate 64 bit
cpu i5-4570
gpu nvidia gt730 4gb ((64 bit faster model)
8 gb ram


Maybe this crash happens on systems with specific software?
Maybe with a specific setting?


can bsnes log? maybe a command line option?

maybe we can compare logs if so and maybe that could help narrow it down.

**Comment by byuu** [comment] 2019-09-10 02:58
ASIO drives are a straight-up trash fire. My ASIO code is 100% literally identical to Steinberg's SDK. And I'll put a $100 bounty on that claim. I have checked every single return code from calling their functions, they all report okay, then when I call the one to start the stream, the backtrace reveals the internals of the drivers themselves are crashing. All of your $500-an-application audio editing software is full of workarounds and tricks to make these drivers work, but since they're closed-source, I can't just copy those workarounds. I have raised this issue with Steinberg, and their company ignored me. So starting with the next release, I'll be disabling ASIO support in bsnes.

**Comment by jjfmz42015** [comment] 2019-09-10 03:07
@byuu what does this mean for the future of bsnes?

**Comment by Marat-Tanalin** [comment] 2019-09-10 03:13
> I have raised this issue with Steinberg, and their company ignored me.

Did you try to ask on the Steinberg’s official developer [forum](https://sdk.steinberg.net/)? Steinberg developers (Yvan Grabit and Arne Scheffler) are quite responsive there when there are serious issues like a crash.

**Comment by byuu** [comment] 2019-09-10 04:23
I don't really see a point in an issue no one will ever address.
I brought the issue up with Steinberg here. Someone who works for them even brought their attention to the issue, and still no help. They don't seem to care, so neither do I. v109.2 removes the ASIO driver from bsnes.
https://sdk.steinberg.net/viewtopic.php?f=1&t=332

**Comment by jjfmz42015** [comment] 2019-09-10 11:57
> I don't really see a point in an issue no one will ever address.
> I brought the issue up with Steinberg here. Someone who works for them even brought their attention to the issue, and still no help. They don't seem to care, so neither do I. v109.2 removes the ASIO driver from bsnes.
> https://sdk.steinberg.net/viewtopic.php?f=1&t=332

Are you doing this because you believe its what is causing the crash?

**Comment by Screwtapello** [comment] 2019-09-10 13:37
@Marat-Tanalin mentioned an ASIO-related crash in https://github.com/byuu/bsnes/issues/100#issuecomment-529706376 so that's one source of crashing dealt with. byuu also [investigated a snow-related crash](https://twitter.com/byuu_san/status/1171003706982031360) although I don't think he managed to track it down.

It sounds like there's still other sources of crashing in v109, and this issue should stay open until we've identified them all, or v110 comes out and we don't care about v109 issues any more.

**Comment by xZabuzax** [comment] 2019-09-11 01:05
Now that all of you are talking about crashes related to driver issues in sound or whatever I need to point out that I'm using "Breakaway Audio Enhancer", that's a cool software that enhances the audio in all the applications in the computer, I've been using that software for a decade now and I've never had issues with it in any application or emulators and my god, that application actually rocks, if none of you have heard of it then give it a try.

Anyways, I'm not sure if my crashes could be related with that application but is worth pointing out that I'm using an audio enhancer in my PC.

Again, I've never had crashes with bsnes before, v109 is the only version so far that is crashing for me.

**Comment by jjfmz42015** [comment] 2019-09-11 03:15
I cant get 109 to crash. being honest.

**Comment by Screwtapello** [comment] 2019-09-11 03:51
@jjfmz42015 That's fine; even if you managed to test every possible combination of every single option, there'd still be millions of combinations of drivers and OS versions and faster/slower hardware and other things that could expose latent problems.

**Comment by jjfmz42015** [comment] 2019-09-11 14:56
> @jjfmz42015 That's fine; even if you managed to test every possible combination of every single option, there'd still be millions of combinations of drivers and OS versions and faster/slower hardware and other things that could expose latent problems.
@Screwtapello yes this is always true.

**Comment by byuu** [comment] 2019-09-13 13:17
Fixed in v109.3, thanks!

**Closed by byuu** 2019-09-13 13:17 UTC
Labels: bug

**Comment by Marat-Tanalin** [comment] 2019-09-13 18:38
bsnes nightly v109.3 still crashes when closing under Windows 7.

**Comment by xZabuzax** [comment] 2019-09-14 05:09
> Looks like crashes happen when closing bsnes with no game loaded/running previously. If a game was once loaded (and then optionally unloaded), closing bsnes does not cause a crash.

This is correct, I haven't tried v109.3 yet but in v109 it was crashing when I opened bsnes and close it without loading a game but still, the crash was random.

I also want to mention that in my PC I fiddled with the power options and changed the maximum processor state from 100% to 99%, the reason I did that is because this CPU tends to get hot and since I use video editing softwares to convert videos and stuff I needed to keep the CPU as cool as possible because it was getting way too hot at 100%.

I don't think that's relevant with the crashes but I believe is better if I provided more information about my current setup.

**Comment by Screwtapello** [comment] 2019-09-14 05:37
People who are having crashes, what version of Windows are you using? AMD or nVidia? Are you using a laptop with a "gaming" and a "regular" GPU? What drivers inside bsnes are you using? Direct3D or OpenGL? DirectSound or WASAPI?

**Comment by xZabuzax** [comment] 2019-09-14 06:21
> People who are having crashes, what version of Windows are you using? AMD or nVidia? Are you using a laptop with a "gaming" and a "regular" GPU? What drivers inside bsnes are you using? Direct3D or OpenGL? DirectSound or WASAPI?

I've provided my PC Specs in the first post. This is what I've found so far regarding v109:

OpenGL 3.2 + audio drivers doesn't cause any crash. (ASIO is the only one crashing)

Direct3D 9.0 + ASIO, DirectSound 7.0 and waveOUT cause the crash.  It doesn't crash with XAudio 2.1 and WASAPI.

DirectDraw 7.0 + ASIO, DirectSound 7.0 and waveOUT cause the crash.  It doesn't crash with XAudio 2.1 and WASAPI.

GDI + ASIO and DirectSound 7.0 cause the crash.  It doesn't crash with XAudio 2.1, WASAPI and waveOUT.

**Comment by xZabuzax** [comment] 2019-09-14 20:34
I hate to double post but I edited my last comment quite a few times while I was testing v109.3, I'm just posting again in case you guys missed the few edits I provided above.

**Comment by Marat-Tanalin** [comment] 2019-09-15 00:12
@Screwtapello

> People who are having crashes, what version of Windows are you using? AMD or nVidia? Are you using a laptop with a "gaming" and a "regular" GPU? What drivers inside bsnes are you using? Direct3D or OpenGL? DirectSound or WASAPI?

Tested more thouroughly and discovered that bsnes 109.3 crashes on close _regardless_ of video and audio drivers (tried all of them), and **stops** crashing after switching the Input driver from the “Windows” value to the “None” value.

* OS: Windows 7 Home Premium SP1 (build 7601) (64-bit).
* CPU: Core i3-2100T.
* RAM: 8 GB.
* GPU: nVidia GTS 250 (2GB) with driver v342.01 (the latest one with support for GTS 250).
* Keyboard: Logitech “K120 for Business” with the standard Windows driver.
