### ISSUE TITLE
Rendering Ranger R2 (Japan) (En) - freezes [bsnes v112]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#189] opened 2019-10-23 20:24 UTC
This one took a long time to reproduce and I'm still not sure how to do it. When you play the first level there is a possibility that the game freezes at the first blue beam (**Edit:** I think rewind and dsp fast was enabled, but I'm not sure):

https://streamable.com/f7up8
![image](https://user-images.githubusercontent.com/53529402/67431272-35794780-f5e4-11e9-8f7f-c991dbe80d32.png)

-------------------

The second thing that could happen is that the music doesn't play at all (with dsp and rewind enabled or disabled):

https://streamable.com/fhfag

**Comment by byuu** [comment] 2019-10-23 20:29
What is (Japan) (En)? Is this a fan translation or something? Again, I only support licensed, official games. My guess would be that this title doesn't work with the fast DSP because it's poorly coded, and the fan translation changed the ROM title so the fast DSP disable isn't being matched.

**Comment by Max833** [comment] 2019-10-23 20:55
> What is (Japan) (En)? Is this a fan translation or something?

No, I think because this game was only released in Japan, but everything is in English: https://en.wikipedia.org/wiki/Rendering_Ranger:_R2

**Comment by CharlesCorrin** [comment] 2019-10-23 22:38
(Japan) (En) is indeed the official release for the game. No-Intro uses language tags when the game has a different language than its default region. Rendering Ranger is in English. Hence No-Intro uses the (En) tag in the filename. I suppose they never considered the possibility people would mistake it for someone's fan translation.

**Comment by byuu** [comment] 2019-10-25 05:03
In any case, please try to get a more consistently reproducible case for this if it's possible.

**Comment by Max833** [comment] 2019-10-26 14:17
Okay, next week I will try to reproduce this more consistently.

**Comment by byuu** [comment] 2019-10-27 04:31
I reverted the Kishin Douji Zenki - Tenchi Meidou fix as being errant, and I also improved some SMP cycle timing regressions from v103.2. I am *hoping* this will fix whatever's up with Rendering Ranger R2 for you. In any case, I can't reproduce it, so ... fingers crossed. Be sure to test against the newest WIP if you test this again.

![Screenshot_2019-10-27_13-31-04](https://user-images.githubusercontent.com/2107894/67629751-fdad2100-f8bd-11e9-9812-1552b5958b12.png)

**Comment by Max833** [comment] 2019-10-27 08:03
Yep, works like a charm now! :)

**Comment by Max833** [comment] 2019-10-27 08:32
Okay, there is still a problem. >_> As soon as I have more info I will let you know.

**Comment by byuu** [comment] 2019-10-27 10:53
> Anyway, I need a break. >_>

You and me both.

**Comment by FitzRoyX** [comment] 2019-10-28 08:23
There's no correlation here to changing settings. I have been able to trigger this hang by dying and starting over repeatedly until it triggers. You do not have to reset the system, just fast forward over cliffs and start new games until it hangs. The hang will always occur in level and it usually happens by you're 10th start over.

I've also been able to trigger it on higan 106, bsnes 073, and snes9x 1.60. But not Mesen-S. Since snes9x and bsnes share the same SMP code and Mesen doesn't, it's likely the problem is there. However, it would be a good idea to test the game on hardware because it has a history. If you can game over yourself 30 times in a row on hardware without triggering it, then it's probably an emulator bug.

**Comment by Max833** [comment] 2019-10-28 15:20
> There's no correlation here to changing settings. I have been able to trigger this hang by dying and starting over repeatedly until it triggers. You do not have to reset the system, just fast forward over cliffs and start new games until it hangs. The hang will always occur in level and it usually happens by your 10th start over.

Oh, you're right. Thank you! :)

> However, it would be a good idea to test the game on hardware because it has a history. If you can game over yourself 30 times in a row on hardware without triggering it, then it's probably an emulator bug.

I will test this next weekend.

**Comment by Molive-0** [comment] 2019-10-28 20:58
So I've been trying this a bunch on hardware.
So far I haven't made the game actually fully crash, but I have entered the first level without sound on hardware, which was described earlier in the issue. (This only happened once in many many tries)
I have also managed to make the game *seem* like it crashed - by holding down start at the start of the level there's a chance that the game will pause on the first frame. Simply press start again and it unpauses.
Are you sure you aren't experiencing a pause on the first frame @Max833 ?

**Comment by byuu** [comment] 2019-10-29 01:51
We know the game was written by a one-man team and only released in a limited run in Japan. It's likely the game is just poorly programmed and hitting a race condition. The SMP core is unbelievably polished and cycle-accurate in the absolute extreme at this point. From v073 to v112 spans so many revisions and rewrites as well.

I think what we need to do is expose the SMP frequency setting and find one that is reliable for this game in particular and mark it as an emulator game hotfix.

**Comment by byuu** [comment] 2019-10-30 22:45
For once I was exactly right, this game is just poorly programmed. I added a game-specific hotfix to set the APU frequency to 32000*768hz instead of 32040*768hz, which allows me to run level 1 twenty times in a row without any crashes. Not saying it won't ever crash, but it's clearly bad CPU<>SMP synchronization if the game outright crashes if it's not perfect, so I consider this a game bug and not a higan/bsnes bug.

**Closed by byuu** 2019-10-30 22:45 UTC
Labels: question

**Comment by Max833** [comment] 2019-11-01 15:39
Thank you! I couldn't reproduce this on hardware as well. Seems to be pretty hard to trigger.
